title: "Cianorte Card Masters"
description: "Conteúdo para jogadores de card games, RPG e jogos de tabuleiro em Cianorte."
baseurl: "/cianortecardmaster"
url: ""
timezone: America/Sao_Paulo
lang: pt-BR

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  guias:
    output: true
    permalink: /guias/:name/
  decks:
    output: true
    permalink: /decks/:name/
  blog:
    output: true
    permalink: /blog/:name/
  comunidade:
    output: true
    permalink: /comunidade/:name/

defaults:
  - scope:
      path: ""
      type: "guias"
    values:
      layout: post
      author: "Cianorte Card Masters"
  - scope:
      path: ""
      type: "decks"
    values:
      layout: post
      author: "Cianorte Card Masters"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: post
      author: "Cianorte Card Masters"
  - scope:
      path: ""
      type: "comunidade"
    values:
      layout: post
      author: "Cianorte Card Masters"
